name: PHPStan

on:
  push:
    branches: [ "main", "epic/**", "feature/**", "fix/**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql, dom, filter, gd, iconv, json, mysql, openssl, session, simplexml, xml, zip

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPStan
      run: composer stan
