name: PHPUnit

on:
  push:
    branches: [ "main", "epic/**", "feature/**", "fix/**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql, dom, filter, gd, iconv, json, mysql, openssl, session, simplexml, xml, zip

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-clover clover.xml --display-warnings

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
